// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logger-service.proto

package pb_src

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogEntry struct {
	UserId         int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Severity       int32  `protobuf:"varint,2,opt,name=severity,proto3" json:"severity,omitempty"`
	LogType        string `protobuf:"bytes,3,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	Section        string `protobuf:"bytes,4,opt,name=section,proto3" json:"section,omitempty"`
	Description    string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AdditionalData string `protobuf:"bytes,6,opt,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty"`
	// @inject_tag: sql:"type:timestamptz"
	HappenedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=happened_at,json=happenedAt,proto3" json:"happened_at,omitempty"`
	// @inject_tag: sql:"type:timestamptz,default:now()"
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{0}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LogEntry) GetSeverity() int32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *LogEntry) GetLogType() string {
	if m != nil {
		return m.LogType
	}
	return ""
}

func (m *LogEntry) GetSection() string {
	if m != nil {
		return m.Section
	}
	return ""
}

func (m *LogEntry) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *LogEntry) GetAdditionalData() string {
	if m != nil {
		return m.AdditionalData
	}
	return ""
}

func (m *LogEntry) GetHappenedAt() *timestamp.Timestamp {
	if m != nil {
		return m.HappenedAt
	}
	return nil
}

func (m *LogEntry) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type QueryItem struct {
	Param                string   `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryItem) Reset()         { *m = QueryItem{} }
func (m *QueryItem) String() string { return proto.CompactTextString(m) }
func (*QueryItem) ProtoMessage()    {}
func (*QueryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{1}
}

func (m *QueryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryItem.Unmarshal(m, b)
}
func (m *QueryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryItem.Marshal(b, m, deterministic)
}
func (m *QueryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryItem.Merge(m, src)
}
func (m *QueryItem) XXX_Size() int {
	return xxx_messageInfo_QueryItem.Size(m)
}
func (m *QueryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueryItem proto.InternalMessageInfo

func (m *QueryItem) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *QueryItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type LogCreationResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogCreationResponse) Reset()         { *m = LogCreationResponse{} }
func (m *LogCreationResponse) String() string { return proto.CompactTextString(m) }
func (*LogCreationResponse) ProtoMessage()    {}
func (*LogCreationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{2}
}

func (m *LogCreationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCreationResponse.Unmarshal(m, b)
}
func (m *LogCreationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCreationResponse.Marshal(b, m, deterministic)
}
func (m *LogCreationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCreationResponse.Merge(m, src)
}
func (m *LogCreationResponse) XXX_Size() int {
	return xxx_messageInfo_LogCreationResponse.Size(m)
}
func (m *LogCreationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCreationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogCreationResponse proto.InternalMessageInfo

func (m *LogCreationResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *LogCreationResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EntriesRequest struct {
	Limit                int32        `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int32        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Query                []*QueryItem `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EntriesRequest) Reset()         { *m = EntriesRequest{} }
func (m *EntriesRequest) String() string { return proto.CompactTextString(m) }
func (*EntriesRequest) ProtoMessage()    {}
func (*EntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{3}
}

func (m *EntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntriesRequest.Unmarshal(m, b)
}
func (m *EntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntriesRequest.Marshal(b, m, deterministic)
}
func (m *EntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntriesRequest.Merge(m, src)
}
func (m *EntriesRequest) XXX_Size() int {
	return xxx_messageInfo_EntriesRequest.Size(m)
}
func (m *EntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntriesRequest proto.InternalMessageInfo

func (m *EntriesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *EntriesRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *EntriesRequest) GetQuery() []*QueryItem {
	if m != nil {
		return m.Query
	}
	return nil
}

type EntriesResponse struct {
	Entries              []*LogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Count                int64       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EntriesResponse) Reset()         { *m = EntriesResponse{} }
func (m *EntriesResponse) String() string { return proto.CompactTextString(m) }
func (*EntriesResponse) ProtoMessage()    {}
func (*EntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{4}
}

func (m *EntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntriesResponse.Unmarshal(m, b)
}
func (m *EntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntriesResponse.Marshal(b, m, deterministic)
}
func (m *EntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntriesResponse.Merge(m, src)
}
func (m *EntriesResponse) XXX_Size() int {
	return xxx_messageInfo_EntriesResponse.Size(m)
}
func (m *EntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntriesResponse proto.InternalMessageInfo

func (m *EntriesResponse) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *EntriesResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "pb_src.LogEntry")
	proto.RegisterType((*QueryItem)(nil), "pb_src.QueryItem")
	proto.RegisterType((*LogCreationResponse)(nil), "pb_src.LogCreationResponse")
	proto.RegisterType((*EntriesRequest)(nil), "pb_src.EntriesRequest")
	proto.RegisterType((*EntriesResponse)(nil), "pb_src.EntriesResponse")
}

func init() { proto.RegisterFile("logger-service.proto", fileDescriptor_1484f153346fa394) }

var fileDescriptor_1484f153346fa394 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x55, 0xba, 0xdd, 0x8f, 0x4c, 0x44, 0x0b, 0xa6, 0x6a, 0x43, 0x38, 0x10, 0xe5, 0xd2, 0x08,
	0x89, 0x54, 0x5a, 0x0e, 0x08, 0x01, 0x87, 0xaa, 0x20, 0x54, 0x69, 0x2f, 0xb8, 0xbd, 0x47, 0xde,
	0x64, 0x08, 0x96, 0x92, 0xd8, 0xb5, 0x9d, 0x95, 0xf2, 0x1f, 0xf8, 0x3f, 0xfc, 0x3d, 0x14, 0x3b,
	0x59, 0x8a, 0xf6, 0xd0, 0x9b, 0xdf, 0x9b, 0xf7, 0xc6, 0xf3, 0x05, 0x67, 0xb5, 0xa8, 0x2a, 0x54,
	0xef, 0x34, 0xaa, 0x1d, 0x2f, 0x30, 0x93, 0x4a, 0x18, 0x41, 0x16, 0x72, 0x9b, 0x6b, 0x55, 0x44,
	0x6f, 0x2a, 0x21, 0xaa, 0x1a, 0xaf, 0x2c, 0xbb, 0xed, 0x7e, 0x5e, 0x19, 0xde, 0xa0, 0x36, 0xac,
	0x91, 0x4e, 0x98, 0xfc, 0x39, 0x82, 0xd5, 0x46, 0x54, 0xdf, 0x5a, 0xa3, 0x7a, 0x72, 0x01, 0xcb,
	0x4e, 0xa3, 0xca, 0x79, 0x19, 0x7a, 0xb1, 0x97, 0xce, 0xe8, 0x62, 0x80, 0xb7, 0x25, 0x89, 0x60,
	0xa5, 0x71, 0x87, 0x8a, 0x9b, 0x3e, 0x3c, 0x8a, 0xbd, 0x74, 0x4e, 0xf7, 0x98, 0xbc, 0x82, 0x55,
	0x2d, 0xaa, 0xdc, 0xf4, 0x12, 0xc3, 0x59, 0xec, 0xa5, 0x3e, 0x5d, 0xd6, 0xa2, 0xba, 0xef, 0x25,
	0x92, 0x10, 0x96, 0x1a, 0x0b, 0xc3, 0x45, 0x1b, 0x1e, 0xbb, 0xc8, 0x08, 0x49, 0x0c, 0x41, 0x89,
	0xba, 0x50, 0x5c, 0xda, 0xe8, 0xdc, 0x46, 0x1f, 0x53, 0xe4, 0x12, 0x4e, 0x59, 0x59, 0xf2, 0xe1,
	0xcd, 0xea, 0xbc, 0x64, 0x86, 0x85, 0x0b, 0xab, 0x3a, 0xf9, 0x47, 0x7f, 0x65, 0x86, 0x91, 0x4f,
	0x10, 0xfc, 0x62, 0x52, 0x62, 0x8b, 0x65, 0xce, 0x4c, 0xb8, 0x8c, 0xbd, 0x34, 0x58, 0x47, 0x99,
	0x6b, 0x3c, 0x9b, 0x1a, 0xcf, 0xee, 0xa7, 0xc6, 0x29, 0x4c, 0xf2, 0x6b, 0x43, 0x3e, 0x02, 0x14,
	0x0a, 0x99, 0x71, 0xde, 0xd5, 0x93, 0x5e, 0x7f, 0x54, 0x5f, 0x9b, 0xe4, 0x03, 0xf8, 0x3f, 0x3a,
	0x54, 0xfd, 0xad, 0xc1, 0x86, 0x9c, 0xc1, 0x5c, 0x32, 0xc5, 0x1a, 0x3b, 0x37, 0x9f, 0x3a, 0x30,
	0xb0, 0x3b, 0x56, 0x77, 0x68, 0x67, 0xe6, 0x53, 0x07, 0x92, 0x1b, 0x78, 0xb9, 0x11, 0xd5, 0xcd,
	0x90, 0x88, 0x8b, 0x96, 0xa2, 0x96, 0xa2, 0xd5, 0x48, 0xce, 0x61, 0xa1, 0x50, 0x77, 0xb5, 0x19,
	0x73, 0x8c, 0x68, 0x48, 0x82, 0x4a, 0x09, 0x35, 0x25, 0xb1, 0x20, 0x29, 0xe0, 0x64, 0xd8, 0x19,
	0x47, 0x4d, 0xf1, 0xa1, 0x43, 0x6d, 0x75, 0x35, 0x6f, 0xb8, 0xb3, 0xcf, 0xa9, 0x03, 0x84, 0xc0,
	0xb1, 0x64, 0x15, 0x8e, 0x5b, 0xb3, 0x6f, 0x72, 0x09, 0xf3, 0x87, 0xa1, 0xf2, 0x70, 0x16, 0xcf,
	0xd2, 0x60, 0xfd, 0x22, 0x73, 0xc7, 0x92, 0xed, 0xdb, 0xa1, 0x2e, 0x9e, 0xdc, 0xc1, 0xe9, 0xfe,
	0x93, 0xb1, 0xca, 0xb7, 0xb0, 0x44, 0x47, 0x85, 0x9e, 0x75, 0x3f, 0x9f, 0xdc, 0xd3, 0x15, 0xd1,
	0x49, 0x30, 0x54, 0x54, 0x88, 0xae, 0x35, 0xf6, 0xf3, 0x19, 0x75, 0x60, 0xfd, 0xdb, 0x83, 0x67,
	0x1b, 0x7b, 0xb3, 0x77, 0xee, 0x64, 0xc9, 0x67, 0x08, 0xec, 0x34, 0xd0, 0x5d, 0xe1, 0x41, 0xc6,
	0xe8, 0xf5, 0x23, 0xe6, 0x60, 0x6e, 0x5f, 0x00, 0xbe, 0xa3, 0x19, 0xeb, 0x24, 0xe7, 0x93, 0xf4,
	0xff, 0xe9, 0x44, 0x17, 0x07, 0xbc, 0xb3, 0x6f, 0x17, 0x76, 0xcb, 0xef, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x2a, 0xee, 0x00, 0x07, 0x48, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerServiceClient is the client API for LoggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerServiceClient interface {
	CreateEntry(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogCreationResponse, error)
	GetEntries(ctx context.Context, in *EntriesRequest, opts ...grpc.CallOption) (*EntriesResponse, error)
}

type loggerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoggerServiceClient(cc *grpc.ClientConn) LoggerServiceClient {
	return &loggerServiceClient{cc}
}

func (c *loggerServiceClient) CreateEntry(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogCreationResponse, error) {
	out := new(LogCreationResponse)
	err := c.cc.Invoke(ctx, "/pb_src.LoggerService/CreateEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerServiceClient) GetEntries(ctx context.Context, in *EntriesRequest, opts ...grpc.CallOption) (*EntriesResponse, error) {
	out := new(EntriesResponse)
	err := c.cc.Invoke(ctx, "/pb_src.LoggerService/GetEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServiceServer is the server API for LoggerService service.
type LoggerServiceServer interface {
	CreateEntry(context.Context, *LogEntry) (*LogCreationResponse, error)
	GetEntries(context.Context, *EntriesRequest) (*EntriesResponse, error)
}

// UnimplementedLoggerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServiceServer struct {
}

func (*UnimplementedLoggerServiceServer) CreateEntry(ctx context.Context, req *LogEntry) (*LogCreationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntry not implemented")
}
func (*UnimplementedLoggerServiceServer) GetEntries(ctx context.Context, req *EntriesRequest) (*EntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntries not implemented")
}

func RegisterLoggerServiceServer(s *grpc.Server, srv LoggerServiceServer) {
	s.RegisterService(&_LoggerService_serviceDesc, srv)
}

func _LoggerService_CreateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).CreateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_src.LoggerService/CreateEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).CreateEntry(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggerService_GetEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).GetEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_src.LoggerService/GetEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).GetEntries(ctx, req.(*EntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoggerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb_src.LoggerService",
	HandlerType: (*LoggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntry",
			Handler:    _LoggerService_CreateEntry_Handler,
		},
		{
			MethodName: "GetEntries",
			Handler:    _LoggerService_GetEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logger-service.proto",
}
